/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Attribute {
  name: string
  value?: Array<AttributeValue>
  start: Position
  end: Position
}

export type AttributeValue =
  | { type: 'Text', content: string, start: Position, end: Position }
  | { type: 'Expression', content: string, start: Position, end: Position }

export interface Expression {
  content: string
  start: Position
  end: Position
}

/** AST节点类型，代表WXML文档中的各种元素 */
export type Node =
  | { type: 'Element', name: string, attrs: Array<Attribute>, children: Array<Node>, selfClosing: boolean, firstAttrSameLine: boolean, start: Position, end: Position }
  | { type: 'Text', content: string, start: Position, end: Position }
  | { type: 'Comment', content: string, start: Position, end: Position }
  | { type: 'Expression', content: string, start: Position, end: Position }

/** 将 WXML 模板字符串解析为抽象语法树 */
export declare function parse(source: string): Root

/** 定义位置信息，用于标记AST节点在源码中的位置 */
export interface Position {
  /** chars 索引, 从 0 开始 */
  offset: number
  /** 行号，从1开始 */
  line: number
  /** 列号，从1开始 */
  column: number
}

export interface Root {
  children: Array<Node>
  start: Position
  end: Position
}

/** Syntax error when parsing tags, not `<script>` or `<style>` tag. */
export interface SyntaxError {
  kind: SyntaxErrorKind
  offset: number
  line: number
  column: number
}

export declare const enum SyntaxErrorKind {
  ExpectAttrName = 0,
  ExpectAttrValue = 1,
  ExpectCloseTag = 2,
  ExpectComment = 3,
  ExpectDoctype = 4,
  ExpectElement = 5,
  ExpectFrontMatter = 6,
  ExpectIdentifier = 7,
  ExpectMustacheInterpolation = 8,
  ExpectSelfCloseTag = 9,
  ExpectTagName = 10,
  ExpectTextNode = 11,
  ExpectExpression = 12
}

export type Value =
  | { type: 'Text', content: string, start: Position, end: Position }
  | { type: 'Expression', content: string, start: Position, end: Position }
